


{{--@php--}}
{{--header( "Content-type: text/html");--}}
{{--header( "Content-Disposition: attachment;Filename=myfile.doc");--}}

{{--@endphp--}}
<!doctype html>


<html>
<head>
    <title>Form</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">


</head>
<body id="form-print-body">
<div id="print-area" class="enrollment-form-body">
    <div style="text-align: center" class="enrollment-form-header">

        <img class="enrollment-laoag-seal" width="100" height="100"    src="{{asset('images/enrollment form/laoag seal.png')}}" alt="">

            <div class="deped-banner">
            <img class="enrollment-deped-logo"   width="70" height="50"      src="{{asset('images/enrollment form/deped.png')}}" alt="">
                <p style="margin-bottom: -9px">Region 1, Schools Division of Laoag City</p>

                <p style="margin-bottom: -9px" >ILOCOS NORTE COLLEGE OF ARTS AND TRADES</p>

                <p style="margin-bottom: -9px" >BRGY.5, P.GOMEZ ST., LAOAG CITY</p>

                <p style="margin-bottom: -9px" >SENIOR HIGH SCHOOL</p>
                <p>(077)600-51-99 | incat.shs@gmail.com | School ID 300373</p>
            </div>
           <img class="incat-logo" width="100" height="100"    src="{{asset('images/enrollment form/incat.png')}}" alt="">
        </div>


    <h2 class="basic-enrollment-banner" style="">Basic Education Enrollment Form</h2>
    <div class="first-line">
        <p><span>School year:</span> {{$student->schoolYear1}} - {{$student->schoolYear12}}  </p>
        @if(!empty($student->lrnNo))
        <p><span>Lrn: </span> With Lrn</p>
            @elseif(empty($student->lrnNo))
        <p><span>Lrn:</span> No Lrn</p>
            @endif



        @if(!empty($student->lastSchool))
        <p>Returning(Balik-Aral)</p>
            @elseif(empty($student->lastSchool))
        <p>Not Returning(Balik-Aral)</p>
            @endif

    </div>

    <div class="enrollment-form-note">
        <p><span>Note:</span> All information that is generated by the system is the same with the information you've provided during enlistment/enrollment period. In case of correction or change in information please ask your registrar, don't correct the form by yourself.  </p>
    </div>

    <div class="student-info-print">
        <h2 class="student-info-print-banner">Student Information</h2>
    <p><span>Psa Birth Certificate No.:</span> {{$student->psaNo}}</p>
        <p><span>Learner Reference No.(LRN):</span> {{$student->lrnNo}}</p>
        <p><span>LAST NAME :</span> {{$student->lastName}}</p>
        <p><span>FIRST NAME :</span> {{$student->firstName}}</p>
        <p><span>MIDDLE NAME :</span> {{$student->middleName}}</p>
        @if(!empty($student->extName))
        <p><span>EXTENSION NAME :</span> {{$student->extName}}</p>
        @elseif(empty($student->extName))
            <p><span>EXTENSION NAME :</span> N/A</p>
        @endif
        <p><span>Date Of birth: </span>{{$student->dob}}</p>
        @if($student->sex == 1)
        <p><span>Sex: </span> Male</p>
            @elseif($student->sex == 2)
            <p><span>Sex: </span> Female</p>
            @endif
        <p><span>AGE: </span> {{$student->age}}</p>
        @if(!empty($student->indigenous))
        <p><span>Indigenous: </span> {{$student->indigenous}}</p>
        @elseif(empty($student->indigenous))
            <p><span>Indigenous: </span> N/A</p>
            @endif
        <p><span>Mother Tongue: </span>{{$student->mothertongue}}</p>
        <div style="text-align: center" class="enrollment-form-address row">
            <p id="enrollment-form-address-banner">Address: </p>
            <div  class="housenumber col-1">
            <p>{{$student->houseNumber}}</p>
                <span >House #</span>
            </div>
            <div  class="street col">
                <p>{{$student->street}}</p>
                <span>Street</span>
            </div>
            <div  class="barangay col">
                <p>{{$student->barangay}}</p>
                <span>Barangay</span>
             </div>
            <div  class="municipality col">
                <p>{{$student->municipality}}</p>
                <span>Municipality</span>
            </div>
            <div  class="province col">
                <p>{{$student->province}}</p>
                <span>Province</span>
            </div>
            <div class="country col">
                <p>{{$student->country}}</p>
                <span>Country</span>
            </div>
            <div class="zip col">
                <p>{{$student->zip}}</p>
                <span>zip</span>
            </div>
        </div>
    <div class="enlistment-guardian-info">
    <p class="enlistment-guardian-info-banner">Parents/Guardian's Information</p>
    <div class="row">
    <p  class="col"><span>Father's Name: </span> {{$student->fatherName}}</p>
    <p  class="col"><span>Mother's Name: </span> {{$student->motherName}}</p>
    </div>


        <p><span>Guardian's Name: </span> {{$student->guardianName}}</p>
        <div class="row">
        <p class="col"><span>Cellphone Number: </span> {{$student->parentCpNo}}</p>
        <p class="col"><span>Telephone Number: </span> {{$student->parentTpNo}}</p>
         </div>
    </div>
        {{--@if(!empty($student->lastGrade)|| !empty($student->lastSchoolYear)|| !empty($student->lastSchoolId)|| !empty($student->lastSchool))--}}
<div class="last-school-attended-enlistment-form">
        <p class="last-school-attended-enlistment-form-banner">Last Attended School Details</p>
        <div class="row">
            <p class="col"><span>Last Grade Level Completed:</span>1st year{{$student->lastGrade}}</p>
            <p class="col"><span>Last School Year Completed:</span>2012{{$student->lastSchoolYear}}</p>
        </div>
        <div class="row">
            <p class="col"><span>School Name</span>:Piddig South Central Elementary School {{$student->lastSchool}}</p>
            <p class="col"><span>Last School Id:</span> 2435353223{{$student->lastSchoolId}}</p>
        </div>
        <p><span>School Address:</span> Brgy. 1 cabaroan Piddig ilocos Norte{{$student->lastSchoolAddress}}</p>
</div>
        {{--@endif--}}




         </div>
    </div>
</div>















<div class="second-page">
<h2 class="second-page-banner">FOR LEARNERS in SENIOR HIGH SCHOOL</h2>
    <div class="second-page-course-border">
    <div class="course-second-page">
        <div class="row justify-content-center">
            <p class="col-2"><span>Semester: </span> {{$student->semester}}</p>
            <p class="col-2"><span>Track: </span> {{$student->track}}</p>
            <p><span>Strand: </span> {{$student->strand}}</p>
        </div>


    </div>

    <div  class="permit-second-page row justify-content-center">
        <p>I hereby certify that the above information given are true and correct to the best of my knowledge <br>
            and I allow the Department of Education to use my child details to create and/or upate his/her learner profile in the
            <br>Learner Information System.  The information herein shall be treated as confidential in compliance with the Data Privacy
            <br> Act of 2012.</p>

    </div>
        <div class="second-page-parent-signature row justify-content-center">

        <p  class="col-5">Signature Over Printed Name of Parent/Guardian</p>
        <p style="margin-left: 200px" class="col-2">Date</p>
        </div>
    </div>
    <div class="second-page-deped-personel">
        <p class="second-page-deped-personel-note">For use of Deped Personnel Only. To be filled up by the <span>Class Adviser</span>. </p>

        <div class="second-page-deped-personel-date row justify-content-center">
            <p class="col-4" style="margin-right: -50px">DATE OF FIRST ATTENDANCE</p>

            <div   style="padding: 15px; border: black solid 1px;width: 15px"></div>
            <div   style="padding: 15px; border: black solid 1px;width: 15px;margin-right: 30px"></div>

            <div   style="padding:15px; border: black solid 1px;width: 15px"></div>
            <div   style="padding: 15px; border: black solid 1px;width: 15px;margin-right: 30px"></div>

            <div   style="padding: 15px; border: black solid 1px;width: 15px"></div>
            <div   style="padding: 15px; border: black solid 1px;width: 15px"></div>
            <div   style="padding: 15px; border: black solid 1px;width: 15px"></div>
            <div   style="padding: 15px; border: black solid 1px;width:15px"></div>

        </div>

        <div class="second-page-deped-personel-grade row justify-content-center">
            <p style="margin-right: -120px;margin-left: 50px" class="col-5">Grade level ___________________</p>
            <p class="col-6">Track(for Shs) ___________________________</p>
        </div>

        <div class="second-page-deped-personel-requirements">

               <p>DOCUMENTS SUBMITTED</p>


            <div class="row justify-content-center">
            <div class="col-3">

                <div class="row">
                <div   style="padding:15px; border: black solid 1px;width: 15px"></div>
                <span>SF 9</span>
                </div>

                <div class="row">
                    <div   style="padding:15px; border: black solid 1px;width: 15px"></div>
                <span>Photocopy of Birth Certificate</span>
                </div>
                <div class="row">
                    <div   style="padding:15px; border: black solid 1px;width: 15px"></div>
                <span>Certificate of Good Moral</span>
                </div>
            </div>
                <div class="col-3">

                    <div class="row">
                        <div   style="padding:15px; border: black solid 1px;width: 15px"></div>
                        <span>SF 10</span>
                    </div>

                    <div class="row">
                        <div   style="padding:15px; border: black solid 1px;width: 15px"></div>
                        <span>NCAE RESULT(Acad Only)</span>
                    </div>
                    <div class="row">
                        <div   style="padding:15px; border: black solid 1px;width: 15px"></div>
                        <span>PEPT Result/ A&E Test(ALS)</span>
                    </div>
                </div>
            </div>
        </div>


    </div>

    <div class="second-page-medical">
        <h2>MEDICAL/DENTAL PROFILING</h2>

        <div class="row justify-content-center second-page-medical-dr">
            <p class="col-5">Dr. MARLON B. DALLO - Medical Officerr III</p>
            <p style="margin-left: 50px" class="col-5">Dr. ZENON I. DEL ROSARIO- DENTIST II</p>
        </div>

        <h2 class="admitted-by">ADMITTED BY</h2>
        <div class="row">
            <p class="col-5 signature-enrolling-officer">Signature Over Printed Name of the Enrolling Officer</p>

        </div>

    </div>



</div>

<script>

    window.onafterprint = function(e){
        $(window).off('mousemove', window.onafterprint);

        console.log('Print Dialog Closed..');
    };

    window.print();

    setTimeout(function(){
        $(window).on('mousemove', window.onafterprint);
        window.history.back();
    }, 1);

</script>

{{--<script type="text/javascript">--}}

    {{--function codespeedy() {--}}
        {{--var print_div = document.getElementById("print-area");--}}
        {{--var print_area = window.open();--}}
        {{--print_area.document.write(print_div.innerHTML);--}}
        {{--print_area.document.close();--}}
        {{--print_area.focus();--}}
        {{--print_area.print();--}}
        {{--print_area.close();--}}
    {{--}--}}
{{--</script>--}}

</body>
</html>